module.exports = {
  OK: 200,
  CREATED: 201, // Successful POST Request
  UPDATED: 200, // Successful PUT/PATCH Request
  DELETED: 204, // Successful DELETE Request
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404, // API Resource NOT Found
  DUPLICATED_ENTRY: 409,
  VALIDATION_ERROR: 418,
  INVALID_OPERATION: 419,
  INVALID_EMAIL_OR_PASSWORD: 470,
  TOKEN_EXPIRED: 471, //JWT expired token
  ITEM_NOT_FOUND: 477,
  INTERNAL_SERVER_ERROR: 500,
};
